### ISSUE TITLE
PG::NotNullViolation: ERROR: null value in column "id" violates not-null constraint

### ISSUE THREAD

**Issue by drj17** [jnunemaker/flipper#343]
I'm getting this error whenever I try to create a feature, add an actor to an existing feature, etc.  Everything is still working on my production environment but my local build is totally messed up now.  Any ideas what might be going on?

```
Flipper::Adapters::ActiveRecord::Feature Load (2.6ms)  SELECT "public"."flipper_features".* FROM "public"."flipper_features" WHERE "public"."flipper_features"."key" = $1  [["key", "test_test"]]
   (0.2ms)  BEGIN
  SQL (0.7ms)  INSERT INTO "public"."flipper_features" ("key", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"  [["key", "test_test"], ["created_at", 2018-03-02 16:04:11 UTC], ["updated_at", 2018-03-02 16:04:11 UTC]]
   (0.1ms)  ROLLBACK
PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, test_test, 2018-03-02 16:04:11.374493, 2018-03-02 16:04:11.374493).
: INSERT INTO "public"."flipper_features" ("key", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id" excluded from capture: No host specified, no public_key specified, no secret_key specified, no project_id specified

ActiveRecord::StatementInvalid (PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, test_test, 2018-03-02 16:04:11.374493, 2018-03-02 16:04:11.374493).
: INSERT INTO "public"."flipper_features" ("key", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"):

activerecord (5.0.2) lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec'
activerecord (5.0.2) lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
activesupport (5.0.2) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
activerecord (5.0.2) lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
activerecord (5.0.2) lib/active_record/connection_adapters/postgresql_adapter.rb:587:in `execute_and_clear'
activerecord (5.0.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
activerecord (5.0.2) lib/active_record/connection_adapters/postgresql/database_statements.rb:137:in `exec_insert'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract/database_statements.rb:124:in `insert'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract/query_cache.rb:17:in `insert'
activerecord (5.0.2) lib/active_record/relation.rb:65:in `insert'
activerecord (5.0.2) lib/active_record/persistence.rb:560:in `_create_record'
activerecord (5.0.2) lib/active_record/counter_cache.rb:128:in `_create_record'
activerecord (5.0.2) lib/active_record/locking/optimistic.rb:75:in `_create_record'
activerecord (5.0.2) lib/active_record/attribute_methods/dirty.rb:123:in `_create_record'
activerecord (5.0.2) lib/active_record/callbacks.rb:302:in `block in _create_record'
activesupport (5.0.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_create_callbacks'
activerecord (5.0.2) lib/active_record/callbacks.rb:302:in `_create_record'
activerecord (5.0.2) lib/active_record/timestamp.rb:68:in `_create_record'
activerecord (5.0.2) lib/active_record/persistence.rb:540:in `create_or_update'
activerecord (5.0.2) lib/active_record/callbacks.rb:298:in `block in create_or_update'
activesupport (5.0.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
activerecord (5.0.2) lib/active_record/callbacks.rb:298:in `create_or_update'
activerecord (5.0.2) lib/active_record/persistence.rb:152:in `save!'
activerecord (5.0.2) lib/active_record/validations.rb:50:in `save!'
activerecord (5.0.2) lib/active_record/attribute_methods/dirty.rb:30:in `save!'
activerecord (5.0.2) lib/active_record/transactions.rb:324:in `block in save!'
activerecord (5.0.2) lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
activerecord (5.0.2) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
activerecord (5.0.2) lib/active_record/transactions.rb:211:in `transaction'
activerecord (5.0.2) lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
activerecord (5.0.2) lib/active_record/transactions.rb:324:in `save!'
activerecord (5.0.2) lib/active_record/suppressor.rb:45:in `save!'
bullet (5.7.0) lib/bullet/active_record5.rb:12:in `save!'
activerecord (5.0.2) lib/active_record/persistence.rb:51:in `create!'
flipper-active_record (0.12.2) lib/flipper/adapters/active_record.rb:53:in `add'
flipper (0.12.2) lib/flipper/adapters/memoizable.rb:48:in `add'
flipper (0.12.2) lib/flipper/feature.rb:77:in `block in add'
flipper (0.12.2) lib/flipper/feature.rb:370:in `block in instrument'
flipper (0.12.2) lib/flipper/instrumenters/noop.rb:5:in `instrument'
flipper (0.12.2) lib/flipper/feature.rb:367:in `instrument'
flipper (0.12.2) lib/flipper/feature.rb:77:in `add'
flipper-ui (0.12.2) lib/flipper/ui/actions/features.rb:44:in `post'
flipper-ui (0.12.2) lib/flipper/ui/action.rb:80:in `block in run'
flipper-ui (0.12.2) lib/flipper/ui/action.rb:80:in `catch'
flipper-ui (0.12.2) lib/flipper/ui/action.rb:80:in `run'
flipper-ui (0.12.2) lib/flipper/ui/action.rb:34:in `run'
flipper-ui (0.12.2) lib/flipper/ui/middleware.rb:48:in `call!'
flipper-ui (0.12.2) lib/flipper/ui/middleware.rb:37:in `call'
flipper (0.12.2) lib/flipper/middleware/memoizer.rb:64:in `memoized_call'
flipper (0.12.2) lib/flipper/middleware/memoizer.rb:42:in `call'
flipper (0.12.2) lib/flipper/middleware/setup_env.rb:35:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
rack-protection (2.0.1) lib/rack/protection/base.rb:50:in `call'
rack-protection (2.0.1) lib/rack/protection/xss_header.rb:18:in `call'
rack-protection (2.0.1) lib/rack/protection/base.rb:50:in `call'
rack-protection (2.0.1) lib/rack/protection/base.rb:50:in `call'
rack-protection (2.0.1) lib/rack/protection/path_traversal.rb:16:in `call'
rack-protection (2.0.1) lib/rack/protection/json_csrf.rb:26:in `call'
rack-protection (2.0.1) lib/rack/protection/base.rb:50:in `call'
rack-protection (2.0.1) lib/rack/protection/base.rb:50:in `call'
rack-protection (2.0.1) lib/rack/protection/frame_options.rb:31:in `call'
rack (2.0.1) lib/rack/auth/basic.rb:25:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
rack (2.0.1) lib/rack/builder.rb:153:in `call'
actionpack (5.0.2) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.0.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:725:in `call'
bullet (5.7.0) lib/bullet/rack.rb:12:in `call'
apartment (2.0.0) lib/apartment/reloader.rb:18:in `call'
apartment (2.0.0) lib/apartment/elevators/generic.rb:23:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
activerecord (5.0.2) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.2) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.2) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
sentry-raven (2.4.0) lib/raven/integrations/rack.rb:50:in `call'
rack-cors (0.4.1) lib/rack/cors.rb:81:in `call'
railties (5.0.2) lib/rails/engine.rb:522:in `call'
puma (3.9.1) lib/puma/configuration.rb:224:in `call'
puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
puma (3.9.1) lib/puma/server.rb:435:in `process_client'
puma (3.9.1) lib/puma/server.rb:299:in `block in run'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

It seems like it's not automatically generating an Id, but why this is the case I have no idea

**Comment by drj17** [comment]
I fixed this for my project by editing the migration to have both tables use a uuid, but I'm still wondering what caused the problem in the first place.

**Comment by jnunemaker** [comment]
Hmmmmm, hard to say. I would have liked to see the schema. It looks like you were adding a feature using the flipper UI. Is that correct? I would expect the active record migration to generate the id field with auto increment automatically. Closing since things are working for you now but if you get any more information, send it my way.
