### ISSUE TITLE
flipper-ui: undefined method `memoizing?' for nil:NilClass

### ISSUE THREAD

**Issue by andyw8** [jnunemaker/flipper#414]
I'm trying to set up Flipper 0.16.2 on a Rails 5.2.3 app.

When I make a request to `/flipper` I get the following error:

```
Started GET "/flipper" for ::1 at 2019-05-25 10:12:08 -0400

NoMethodError (undefined method `memoizing?' for nil:NilClass):

flipper (0.16.2) lib/flipper/middleware/memoizer.rb:53:in `memoized_call'
flipper (0.16.2) lib/flipper/middleware/memoizer.rb:40:in `call'
flipper (0.16.2) lib/flipper/middleware/setup_env.rb:35:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
```
Here's the code where this comes from:
```
flipper = env.fetch(@env_key) { Flipper }
original = flipper.memoizing?
````
Using the Rails web console, I can see that `@env_key` is `'flipper'`.
It seems that `env` does have a key with this name but it's `nil`:

```
>>  @env_key
=> "flipper"
>>  env.fetch('flipper')
=> nil
```

I have tried both the in-memory and ActiveRecord adapters.

**Comment by andyw8** [comment]
Solved: I had misconfigured the lazy-loading.
