### ISSUE TITLE
Flipper with Redis erraticaly fails

### ISSUE THREAD

**Issue by matiasgarcia** [jnunemaker/flipper#597]
For example, we have the feature turned on and can't turn it off:

![Peek 2022-01-10 12-30](https://user-images.githubusercontent.com/2261869/148792608-ea62e47d-e828-41a3-89ec-59961f50b92b.gif)

Dependencies:

```
    flipper (0.22.2)
    flipper-redis (0.22.2)
      flipper (~> 0.22.2)
      redis (>= 2.2, < 5)
    flipper-ui (0.22.2)
      erubi (>= 1.0.0, < 2.0.0)
      flipper (~> 0.22.2)
      rack (>= 1.4, < 3)
      rack-protection (>= 1.5.3, < 2.2.0)
```

**Comment by matiasgarcia** [comment]
This was fixed by changing this:

```
Flipper.configure do |config|
    config.adapter do
      Flipper::Adapters::Redis.new(
        Redis::Store::Factory.create(Settings.redis.flipper_url, serializer: nil)
        Redis.new(url: Settings.redis.flipper_url)
      )
    end
  end
```

To this:

```
Flipper.configure do |config|
    config.adapter do
      Flipper::Adapters::Redis.new(
        Redis.new(url: Settings.redis.flipper_url)
      )
    end
  end
```

What worries me is that Flipper doesn't raise any exception about this... But whatever, I guess the problem was on our end.

**Comment by jnunemaker** [comment]
> What worries me is that Flipper doesn't raise any exception about this... But whatever, I guess the problem was on our end.

@matiasgarcia hi there! I'm a little confused. Was there a problem with flipper? Or just on your end? Seems like your end so I'm going to close the issue. 

That said, you also seem like flipper wasn't doing something it should have been doing. Can you describe what you expected to be different? Are you wanting flipper to warn or raise if you use the redis adapter and pass in the wrong redis instance?

**Comment by jnunemaker** [comment]
@matiasgarcia gotcha. Yeah so the redis adapter ([source](https://github.com/jnunemaker/flipper/blob/54f67ff841624667af6bb02799fdd315cdc9df8c/lib/flipper/adapters/redis.rb))doesn't require a specific redis instance. It more just requires an instance that adheres to the same interface as the Redis.new instance. 

That said, it doesn't swallow any errors. I just double checked and I don't see any rescues in there. I don't believe Feature ([source](https://github.com/jnunemaker/flipper/blob/54f67ff841624667af6bb02799fdd315cdc9df8c/lib/flipper/feature.rb)) uses any rescue's either.

I whipped a from ENV test case together and it indeed raised an error if I change the url to a non-existent redis url:

```ruby
require 'bundler/setup'
require 'logger'

ENV["FLIPPER_REDIS_URL"] = "redis://localhost:6380"
require 'flipper/adapters/redis'

Flipper[:stats].enable
```

When I ran that (note the port is not the default port) I received this:

```
$ bx ruby examples/redis/from_env.rb 
Traceback (most recent call last):
        30: from examples/redis/from_env.rb:7:in `<main>'
        29: from /Users/jnunemaker/github/flipper/lib/flipper/feature.rb:43:in `enable'
        28: from /Users/jnunemaker/github/flipper/lib/flipper/feature.rb:372:in `instrument'
        27: from /Users/jnunemaker/github/flipper/lib/flipper/instrumenters/noop.rb:5:in `instrument'
        26: from /Users/jnunemaker/github/flipper/lib/flipper/feature.rb:375:in `block in instrument'
        25: from /Users/jnunemaker/github/flipper/lib/flipper/feature.rb:44:in `block in enable'
        24: from /Users/jnunemaker/github/flipper/lib/flipper/adapters/memoizable.rb:48:in `add'
        23: from /Users/jnunemaker/github/flipper/lib/flipper/adapters/redis.rb:31:in `add'
        22: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis.rb:1494:in `sadd'
        21: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis.rb:72:in `synchronize'
        20: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
        19: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
        18: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis.rb:72:in `block in synchronize'
        17: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis.rb:1495:in `block in sadd'
        16: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:162:in `call'
        15: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:268:in `process'
        14: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:356:in `logging'
        13: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:269:in `block in process'
        12: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:417:in `ensure_connected'
        11: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:116:in `connect'
        10: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:344:in `with_reconnect'
         9: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:117:in `block in connect'
         8: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:385:in `establish_connection'
         7: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/connection/ruby.rb:305:in `connect'
         6: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/connection/ruby.rb:191:in `connect'
         5: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/connection/ruby.rb:191:in `each_with_index'
         4: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/connection/ruby.rb:191:in `each'
         3: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/connection/ruby.rb:193:in `block in connect'
         2: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/connection/ruby.rb:155:in `connect_addrinfo'
         1: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/2.7.0/socket.rb:1214:in `connect_nonblock'
/Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/2.7.0/socket.rb:1214:in `__connect_nonblock': Operation now in progress - connect(2) would block (IO::EINPROGRESSWaitWritable)
        31: from examples/redis/from_env.rb:7:in `<main>'
        30: from /Users/jnunemaker/github/flipper/lib/flipper/feature.rb:43:in `enable'
        29: from /Users/jnunemaker/github/flipper/lib/flipper/feature.rb:372:in `instrument'
        28: from /Users/jnunemaker/github/flipper/lib/flipper/instrumenters/noop.rb:5:in `instrument'
        27: from /Users/jnunemaker/github/flipper/lib/flipper/feature.rb:375:in `block in instrument'
        26: from /Users/jnunemaker/github/flipper/lib/flipper/feature.rb:44:in `block in enable'
        25: from /Users/jnunemaker/github/flipper/lib/flipper/adapters/memoizable.rb:48:in `add'
        24: from /Users/jnunemaker/github/flipper/lib/flipper/adapters/redis.rb:31:in `add'
        23: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis.rb:1494:in `sadd'
        22: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis.rb:72:in `synchronize'
        21: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
        20: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
        19: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis.rb:72:in `block in synchronize'
        18: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis.rb:1495:in `block in sadd'
        17: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:162:in `call'
        16: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:268:in `process'
        15: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:356:in `logging'
        14: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:269:in `block in process'
        13: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:417:in `ensure_connected'
        12: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:116:in `connect'
        11: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:344:in `with_reconnect'
        10: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:117:in `block in connect'
         9: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:385:in `establish_connection'
         8: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/connection/ruby.rb:305:in `connect'
         7: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/connection/ruby.rb:191:in `connect'
         6: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/connection/ruby.rb:191:in `each_with_index'
         5: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/connection/ruby.rb:191:in `each'
         4: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/connection/ruby.rb:193:in `block in connect'
         3: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/connection/ruby.rb:154:in `connect_addrinfo'
         2: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/connection/ruby.rb:160:in `rescue in connect_addrinfo'
         1: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/2.7.0/socket.rb:1214:in `connect_nonblock'
/Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/2.7.0/socket.rb:1214:in `__connect_nonblock': Connection refused - connect(2) for 127.0.0.1:6380 (Errno::ECONNREFUSED)
        23: from examples/redis/from_env.rb:7:in `<main>'
        22: from /Users/jnunemaker/github/flipper/lib/flipper/feature.rb:43:in `enable'
        21: from /Users/jnunemaker/github/flipper/lib/flipper/feature.rb:372:in `instrument'
        20: from /Users/jnunemaker/github/flipper/lib/flipper/instrumenters/noop.rb:5:in `instrument'
        19: from /Users/jnunemaker/github/flipper/lib/flipper/feature.rb:375:in `block in instrument'
        18: from /Users/jnunemaker/github/flipper/lib/flipper/feature.rb:44:in `block in enable'
        17: from /Users/jnunemaker/github/flipper/lib/flipper/adapters/memoizable.rb:48:in `add'
        16: from /Users/jnunemaker/github/flipper/lib/flipper/adapters/redis.rb:31:in `add'
        15: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis.rb:1494:in `sadd'
        14: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis.rb:72:in `synchronize'
        13: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
        12: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
        11: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis.rb:72:in `block in synchronize'
        10: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis.rb:1495:in `block in sadd'
         9: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:162:in `call'
         8: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:268:in `process'
         7: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:356:in `logging'
         6: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:269:in `block in process'
         5: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:417:in `ensure_connected'
         4: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:116:in `connect'
         3: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:344:in `with_reconnect'
         2: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:117:in `block in connect'
         1: from /Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:379:in `establish_connection'
/Users/jnunemaker/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/redis-4.5.1/lib/redis/client.rb:398:in `rescue in establish_connection': Error connecting to Redis on localhost:6380 (Errno::ECONNREFUSED) (Redis::CannotConnectError)
```

I also tried this and it failed with the same error:

```ruby
require 'bundler/setup'
require 'logger'

require 'flipper/adapters/redis'

Flipper.configure do |config|
  config.adapter {
    Flipper::Adapters::Redis.new(Redis.new(url: "redis://localhost:6380"))
  }
end

p Flipper[:stats].enable
```

Lastly, I passed in an instance for redis that doesn't have the right interface like this:

```ruby
require 'bundler/setup'
require 'logger'

require 'flipper/adapters/redis'

Flipper.configure do |config|
  config.adapter {
    Flipper::Adapters::Redis.new(Object.new)
  }
end

p Flipper[:stats].enable
```

And it errored when it first tried to call a method that didn't exist:

```ruby
require 'bundler/setup'
require 'logger'

require 'flipper/adapters/redis'

Flipper.configure do |config|
  config.adapter {
    Flipper::Adapters::Redis.new(Object.new)
  }
end

p Flipper[:stats].enable
```

My guess would be that something is up with the redis factory stuff.

I also tried this:

```ruby
require 'flipper-redis'

Flipper.configure do |config|
  config.adapter {
    Flipper::Adapters::Redis.new(Redis::Store::Factory.create("redis://localhost:6380"))
  }
end

p Flipper[:stats].enable
```

And it popped the connection error as well. 

Lastly I tried redis store out and it worked fine.

```
$ pry
[1] pry(main)> require "flipper-redis"
=> true
[2] pry(main)> require "redis-store"
=> true
[3] pry(main)> require 'flipper-redis'

Flipper.configure do |config|
  config.adapter {
    Flipper::Adapters::Redis.new(Redis::Store::Factory.create("redis://localhost:6379"))
  }
end
[3] pry(main)> require 'flipper-redis'
Flipper.configure do |config|
  config.adapter {
    Flipper::Adapters::Redis.new(Redis::Store::Factory.create("redis://localhost:6379"))
  }
end
p Flipper[:stats].enable
true
=> true
[4] pry(main)> Flipper.enabled?(:stats)
=> true
[5] pry(main)> Flipper.disable(:stats)
=> true
[6] pry(main)> Flipper.enabled?(:stats)
=> false
```

So I'm not sure what was happening for you, but I don't think it was flipper. 

If you can find different, please let me know so we can get it fixed up. Thanks!

**Comment by matiasgarcia** [comment]
@jnunemaker Which version of redis-store were you using? We have (1.6.0).

**Comment by jnunemaker** [comment]
Looks like 1.9. 

```
$ gem which redis-store
/Users/jnunemaker/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-store-1.9.0/lib/redis-store.rb
```
