### ISSUE TITLE
Problem with flipper-ui and rails 4.2.1

### ISSUE THREAD

**Issue by gssbzn** [jnunemaker/flipper#67]
We recently tried to update to the latest version of the gem for our app and found a problem with the flipper ui that won't even load.

Here is a trace log of the request: 
```console
Started GET "/flipper" for ::1 at 2015-04-28 15:08:59 -0500

NoMethodError (undefined method `each' for #<ActionDispatch::Request::Session:0x7fb5738240f8 not yet loaded>):
  rack (1.6.0) lib/rack/session/abstract/id.rb:158:in `stringify_keys'
  rack (1.6.0) lib/rack/session/abstract/id.rb:95:in `update'
  rack (1.6.0) lib/rack/session/abstract/id.rb:258:in `prepare_session'
  rack (1.6.0) lib/rack/session/abstract/id.rb:224:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  rack (1.6.0) lib/rack/builder.rb:153:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  rack (1.6.0) lib/rack/handler/webrick.rb:89:in `service'
````

And a sample app that reproduce this error: https://github.com/gssbzn/flipper-test

From what I could find there's an Incompatibility between Rack::Session and ActionDispatch::Request::Session that could be the cause of this error. Thanks in advance.

**Comment by jnunemaker** [comment]
Thanks for reporting! I'll dig in.

**Comment by jnunemaker** [comment]
The only reason I needed rack session was for rack protection. It uses it to store the csrf token.

**Comment by jnunemaker** [comment]
Try out beta5 which I'm releasing right now. The gist is that I removed sessions from the default stack for the UI and instead am forcing standalone rack people to include sessions. Easy fix. Since this is used with rails most often it should affect no one.

**Comment by gssbzn** [comment]
Upgraded and everything is working fine, thanks again for a great gem.

**Comment by jnunemaker** [comment]
@gssbzn just glad you are finding it useful!

**Comment by jnunemaker** [comment]
@gssbzn which adapter do you use if you don't mind me asking?

**Comment by gssbzn** [comment]
@jnunemaker right now we are using the ActiveRecord adapter since we are planing to use it to validate access to paid features and don't want to heroku or redis to give us a problem with a missing activation.
