### ISSUE TITLE
Flipper with redis adapter needs a working redis connection during asset precompilation

### ISSUE THREAD

**Issue by AdoPi** [jnunemaker/flipper#712]
Hello,
I'm building a Docker image for my Rails application, during the build process I need to precompile assets.
However, Since I've added Flipper with the Redis adapter it crashes with this error:
```

rake aborted!
Redis::CannotConnectError: Address not available - connect(2) for [::1]:6379
/usr/local/bundle/gems/redis-client-0.14.0/lib/redis_client/ruby_connection.rb:111:in `connect'
/usr/local/bundle/gems/redis-client-0.14.0/lib/redis_client/ruby_connection.rb:49:in `initialize'
/usr/local/bundle/gems/redis-client-0.14.0/lib/redis_client.rb:671:in `new'
/usr/local/bundle/gems/redis-client-0.14.0/lib/redis_client.rb:671:in `block in connect'
/usr/local/bundle/gems/redis-client-0.14.0/lib/redis_client/middlewares.rb:12:in `connect'
/usr/local/bundle/gems/redis-client-0.14.0/lib/redis_client.rb:670:in `connect'
/usr/local/bundle/gems/redis-client-0.14.0/lib/redis_client.rb:[657](https://gitlab.unova.fr/sulf/billetterie/-/jobs/122593#L657):in `raw_connection'
/usr/local/bundle/gems/redis-client-0.14.0/lib/redis_client.rb:624:in `ensure_connected'
/usr/local/bundle/gems/redis-client-0.14.0/lib/redis_client.rb:224:in `call_v'
/usr/local/bundle/gems/redis-5.0.6/lib/redis/client.rb:73:in `call_v'
/usr/local/bundle/gems/redis-5.0.6/lib/redis.rb:167:in `block in send_command'
/usr/local/bundle/gems/redis-5.0.6/lib/redis.rb:166:in `synchronize'
/usr/local/bundle/gems/redis-5.0.6/lib/redis.rb:166:in `send_command'
/usr/local/bundle/gems/redis-5.0.6/lib/redis/commands/sets.rb:21:in `sadd'
/usr/local/bundle/gems/flipper-redis-0.27.1/lib/flipper/adapters/redis.rb:34:in `add'
/usr/local/bundle/gems/flipper-0.27.1/lib/flipper/adapters/memoizable.rb:47:in `add'
/usr/local/bundle/gems/flipper-0.27.1/lib/flipper/feature.rb:44:in `block in enable'
/usr/local/bundle/gems/flipper-0.27.1/lib/flipper/feature.rb:379:in `block in instrument'
/usr/local/bundle/gems/activesupport-7.0.4.3/lib/active_support/notifications.rb:208:in `instrument'
/usr/local/bundle/gems/flipper-0.27.1/lib/flipper/feature.rb:376:in `instrument'
/usr/local/bundle/gems/flipper-0.27.1/lib/flipper/feature.rb:43:in `enable'
/usr/local/bundle/gems/flipper-0.27.1/lib/flipper/dsl.rb:46:in `enable'
config/initializers/feature_flags.rb:1:in `<main>'
```

I have put this line in my config/initializers/feature_flags.rb : 
`Flipper.enable(:my_feature)`

I think Redis connection is not mandatory to precompile assets.
Did I do something wrong?

**Comment by AdoPi** [comment]
Closing as I think this is just a misconfiguration of my initializer.

**Comment by green3g** [comment]
@AdoPi would you be able to elaborate? I know this post is old but I'm having the same issue and was curious what your resolution was. 

Our Flipper instance is crashing the assets precompile process in docker builds because of a feature flag check in active admin I believe.

**Comment by bkeepers** [comment]
@green3g it sounds like something may be doing a feature check at app boot time instead of request runtime. We strongly recommend adapting our feature flag checks to happen at requeest runtime where possible, or in a `after_initialize` block if necessary at runtime.

If you're not getting a stack trace from the assets error, you can track it down by puts-ing the caller:

```ruby
Flipper.configure do |config|
  config.default do |adapter|
    puts "Flipper initialized here", caller
    Flipper.new(adapter)
  end
end
```
